# Homepage Settings
title: Luker
permalink: /:title
url: 'BenLuker.github.io'

# Main Page Banner Settings
banner-title: Benjamin Luker
banner-description: Applied Computer Science undergrad trained in developing with emerging digital practices to produce experiences emphasizing experiential design and human interaction. What does this mean? I combine art and computer science to create things for people to enjoy.
banner-cta: View Demo Reel
banner-cta-link: https://youtu.be/iFmJQnw5dNw
banner-video-thumbnail: 
banner-video-webm: assets/img/main/WebsiteBanner.webm
banner-video-mp4: 

# Featured Posts
featured-work: /works/WISIWYG
featured-blog: /blog/RevealFadeShaderGraph

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

collections:
  works:
    output: true
  blog:
    output: true

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
